# Config

language: c
sudo: false
dist: trusty
cache: bundler
notifications:
  email: false

env:
  - ASTVER=14

# Extend build matrix
matrix:
  include:
    - env: ASTVER=16
    #- env: ASTVER=15
    #- env: ASTVER=14
    - env: ASTVER=13
    #- env: ASTVER=12
    - env: ASTVER=11
    #- env: ASTVER=10
    #- env: ASTVER=1.8

before_install:
  - wget http://junk.devs.nu/a/asterisk/asterisk-$ASTVER-include.tar.bz2
  - tar jxf asterisk-$ASTVER-include.tar.bz2

before_script:
  - aclocal
  - autoconf
  - automake -a || true  # do install stuff, don't create makefile
  - ./configure --with-astversion=$ASTVER --with-asterisk=./asterisk-$ASTVER/include DESTDIR=/tmp

script:
  - make clean all
  - make check
